version: "2.4"
services:
  vroom:
    network_mode: host
    image: vroomproject/vroom-docker:v1.6.0
    container_name: vroom
#    build:  # use this section instead of "image" to build your own image
#      context: .
#      args:
#        - VROOM_RELEASE=v1.6.0
#        - VROOM_EXPRESS_RELEASE=v0.5.0
#    ports:
#      - "3000:3000"  # can be configured if not network_mode=host
    volumes:
      - ./vroom_conf/:/conf
    environment:
      - VROOM_ROUTER=osrm  # or libosrm, ors
    depends_on:
      - ors-app
  # Example for OpenRouteService
  ors-app:
    image: openrouteservice/openrouteservice:latest
    container_name: ors-app
    ports:
      - 8080:8080
    volumes:
        - ./graphs:/ors-core/data/graphs
        - ./elevation_cache:/ors-core/data/elevation_cache
        - ./logs/ors/:/var/log/ors/
        - ./logs/tomcat/:/usr/local/tomcat/logs
