# only builds and tests on tag pushes and PRs to master
# only pushes on tag pushes
name: test & publish
on:
  push:
    branches-ignore:
      - '*'
    tags:
      - '*'
    paths-ignore:
      - '.gitignore'
      - 'docker-compose.yml'
      - 'LICENSE'
      - '**.md'

jobs:
  build_test_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Extract tag name
        id: tag
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}

      - name: Build tagged Image
        run: |
          echo "Building image vroomvrp/vroom-docker:${{ steps.tag.outputs.TAG }}"
          docker build -t vroomvrp/vroom-docker:${{ steps.tag.outputs.TAG }} .

      - name: Test tagged image
        run : sudo /bin/bash -c "./tests/test.sh vroomvrp/vroom-docker:${{ steps.tag.outputs.TAG }}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image
        run: docker push vroomvrp/vroom-docker:${{ steps.tag.outputs.TAG }}
